### ISSUE TITLE
Var vs let

### ISSUE THREAD

**Issue by JimenaEB** [alexcastillla/JS-Excuse-Generator#1]
Los var se usan para variables globales, cosa que es una mala práctica, y los let dentro del scope de una función
https://github.com/alexcastillla/JS-Excuse-Generator/blob/a3f0393cfff6ab2e1838671e4746c9c4d1e462a3/index.js#L4

**Comment by alexcastillla** [comment]
He corregido el código introduciendo las distintas variables Let que tenia fuera de la función en el interior de ella.

**Comment by JimenaEB** [comment]
Muy bien!
