### ISSUE TITLE
+

### ISSUE THREAD

**Issue by JimenaEB** [alexcastillla/JS-Excuse-Generator#2]
Los números se suman, los strings se concatenan
https://github.com/alexcastillla/JS-Excuse-Generator/blob/a3f0393cfff6ab2e1838671e4746c9c4d1e462a3/index.js#L13

**Comment by alexcastillla** [comment]
Perfecto, he quitado la suma y he utilizado un concat con los strings quedando así la linea:

`document.getElementById("answerDocument").innerHTML = firstPartAnswer.concat(" ",whoAnswer," ",didAnswer," ",objectAnswer," ",timeAnswer);`

**Comment by JimenaEB** [comment]
Perfectísimo!
